### ISSUE TITLE
Vanilla Clair Text Speed

### ISSUE THREAD

**Issue by vicendithas** [Dabomstew/pokecrystal-speedchoice#20]
With the Vanilla Clair, Instant Text, and Hold to Mash options turned on, Clair's text when she gives you the badge goes so fast, it is difficult to see what badge she actually gave you. Obviously this only applies to randomizers where the badges are randomized.

**Comment by vicendithas** [comment]
Would it be possible to have it play the "Badge Acquired" sound when the text for the badge is on screen, so that it stays on screen a bit longer?

**Comment by Dabomstew** [comment]
That is meant to be happening so if it isn't it's a bug to fix

**Comment by vicendithas** [comment]
Yeah it's not a bug, more a QoL suggestion.

**Comment by vicendithas** [comment]
So I did some testing on this, hopefully this all makes sense. It turns out that if you don't have Instant Text and Hold to Mash on (or if you are really careful about only pushing the button once), it does actually play the "Badge Acquired" sound and hold the text up for what badge you received until the sound is done playing (like the other Gym Leaders do). However, if you are just holding to mash, the sound doesn't actually play and it skips right over that text box.

What I'm guessing is there is some kind of race condition where the text saying "NAME received BLAHBADGE" displays and the sound is queued to play, but if it receives an input to move past the textbox faster the sound can actually start, then it just skips the sound and the textbox goes away immediately.

In essence, it looks like this is actually a bug between the interaction with Clair's dialogue and the Instant Text/Hold to Mash. It appears that the intended behavior is that the game pauses to display the badge received and plays the sound, but having Instant Text/Hold to Mash breaks that.

**Comment by Dabomstew** [comment]
Oh so it is a form of jingle skip. Good to know. I think I can fix it
anyways

**Comment by Dabomstew** [comment]
Should be fixed by 59c57fa.
