### ISSUE TITLE
verbosesetflag doesn't play a sound when giving non-badge flags

### ISSUE THREAD

**Issue by erudnick-cohen** [Dabomstew/pokecrystal-speedchoice#22]
See title. Code indicates that the "got item" sound should play when receiving a flag (e.g. pokegear from its vanilla location), but no sound is played. This bug has unfortunate interactions with instant text, since it makes it extremely easy for a player to miss seeing that they received a flag.

**Comment by Dabomstew** [comment]
Should be fixed by 59c57fa.
