### ISSUE TITLE
Item Location

### ISSUE THREAD

**Issue by naboknight** [Dabomstew/pokecrystal-speedchoice#26]
Is it possible to put an item's location on a board?
Example: "StormBadge is in Rainbow Wing Gift" or "Rainbow Wing Gift have an important item" 
the map would also help: "StormBadge is in TinTower1F" or "TinTower1F have a...
(I would like to implement this to decrease seed time in randomizer)

**Comment by vicendithas** [comment]
I think this is a great idea, but not something that should be implemented in speedchoice. The goal of speedchoice is to add QOL and options to Pokemon Crystal, but not to implement the randomization itself. This would be a job for the item randomizers. I would suggest talking to ERC about it.

**Comment by naboknight** [comment]
I will talk to ERC, I asked for help because I made some changes to the rom, like opening Mt.Silver with 12 badges, I thought it would be something simple to configure. Thanks for the guidance.
